### ISSUE TITLE
请问appKey如何获得

### ISSUE THREAD

**Issue by sdfasffsdf** [fython/BilibiliAPIDocs#11]
请问appKey如何获得

**Comment by cnbeining** [comment]
没办法

**Comment by alexykuan** [comment]
有没有移动端的api

**Comment by fython** [comment]
@alexykuan 什么叫移动端的 API

**Comment by alexykuan** [comment]
@fython  bilibili手机端的api数据接口

**Comment by fython** [comment]
@alexykuan 应该都是一样的吧，这个 Repo 只拉取官方提供（给第三方）的文档，没有去爬 Bilibili 客户端的接口。

**Comment by alexykuan** [comment]
我反编译只能得到部分的接口。不过还是谢谢你搬运这些接口，新年快乐！

**Comment by weituotian** [comment]
到底怎么搞嘛?

**Comment by fython** [comment]
无解。

**Comment by weituotian** [comment]
@fython 大佬赐教,跪求

**Comment by cnbeining** [comment]
跪我们没用 找官方吧。

当然曾经有一个机会摆在我面前 我表示 你给我revoke了吧 我不要了（

**Comment by weituotian** [comment]
@cnbeining 看到大佬哪有不跪的道理

**Comment by weituotian** [comment]
bilibili现在已经关闭appkey的申请了
@fython 
分享一个appkey: 84956560bc028eb7
![image](https://cloud.githubusercontent.com/assets/7270968/23004824/bf74a994-f433-11e6-8f2f-c6f83bf4a06b.png)

**Comment by xiaokang00010** [comment]
qwq

**Comment by LittleBlacklb** [comment]
尻古

**Comment by xiaokang00010** [comment]
qaq

> 尻古

qaq
