### ISSUE TITLE
官方文档在哪里？

### ISSUE THREAD

**Issue by nuomi** [fython/BilibiliAPIDocs#4]
绝大部分内容根据 http://docs.bilibili.cn/wiki 官方文档进行编写

---

但是这个地址我怎么打不开？
请问还有哪里能够看到官方文档？

**Comment by cnbeining** [comment]
正是因为这破地址打不开才有这个project的。 

要是他的文档说人话 能看见 要我们作甚。。。

![j3 0 kk trrrkw y8hw2ys](https://cloud.githubusercontent.com/assets/1560962/12534790/86f4f176-c236-11e5-9bad-6e79df60b579.gif)

**Comment by nuomi** [comment]
那这项目的信息到底是从哪里来的？

**Comment by cnbeining** [comment]
因为这破地址有时还能打开啊。

加上网页快照。

加上不开放的。

**Comment by nuomi** [comment]
给你们跪了。。。。

**Comment by Qixingchen** [comment]
官方现在已经炸了,如果有耐心,在等几个月看看还能不能上.

官方wiki上所有api页面都已经贴在这里了
~~另外还顺带维护了下多年没更新的文档~~

**Comment by smallpotato000** [comment]
也就是说API现在其实是不开放的？之前有把那个HTML文件放在自己网站上但是申请API还是提示打不开其实是这个原因？

**Comment by cnbeining** [comment]
的确不开放。

但是你如果想用bilograb的key 我也没法revoke。就没有第三方登陆了。

2016年1月24日星期日，smallpotato000 notifications@github.com 写道：

**Comment by smallpotato000** [comment]
于是看起来用正则表达式解析网页内容好像更简单？

**Comment by cnbeining** [comment]
我更建议使用API。

否则你需要考虑如何在爬虫中执行JS，这会造成很大的浪费。

**Comment by rf695** [comment]
给大B站跪了。

**Comment by fython** [comment]
@cnbeining 同意，写爬虫还及时适配官方前端一些小改动，太麻烦了。

**Comment by cnbeining** [comment]
我在想尽可能把第三方登陆拿回来。但是不简单。

2016年1月29日星期五，烧饼 notifications@github.com 写道：
