### ISSUE TITLE
话说 docs.bilibili.cn 这个站点真的存在吗

### ISSUE THREAD

**Issue by KaiserKatze** [fython/BilibiliAPIDocs#8]
IP倒是能解析
但ping之超时
:D

**Comment by cnbeining** [comment]
存在。

2016年5月28日星期六，Nymphoenix notifications@github.com 写道：

**Comment by donizyo** [comment]
不会是公司内网吧 QAQ

**Comment by KaiserKatze** [comment]
给个IP看看对不对吧 QAQ

**Comment by cnbeining** [comment]
当年不是内网。

现在逼站已经不是那个时代了。

**Comment by donizyo** [comment]
_(:зゝ∠)_ 嘛，你是怎么看到内网的呀

**Comment by KaiserKatze** [comment]
嘛，你是怎么看到内网的呀 `_(:зゝ∠)_`

**Comment by KaiserKatze** [comment]
我其实想找上传视频的脚本 _(:зゝ∠)_

**Comment by cnbeining** [comment]
抓包写一个吧。并不很困难。

2016年5月30日星期一，Nymphoenix notifications@github.com 写道：

**Comment by KaiserKatze** [comment]
_(:зゝ∠)_  但并不会用WireShark抓包诶，这东西下载好久了根本没学会huh

**Comment by xuxiaohu** [comment]
同问，好像访问不了，是不是内网，外部无法访问

**Comment by KaiserKatze** [comment]
@xuxiaohu 
只能抓包玩了_(:зゝ∠)_
话说 xuxiaohu 懂怎么处理 Https Chunk 吗？

**Comment by Qixingchen** [comment]
​api文档上有的​已经全部在这里了,那个文档早就不在维护了

2016-06-02 12:24 GMT+08:00 donizyo notifications@github.com:

**Comment by KaiserKatze** [comment]
就算有登陆 API，还要申请权限来测试，很麻烦啊 :D

> #### 调用地址
> 
> https://api.bilibili.tv/login
> 需要 App Key；此API调用权限需要额外申请，具体请联系网站客服。

**Comment by cnbeining** [comment]
没有API 不开放申请新的API 老API我知道的全封杀了 自求多福吧您。

**Comment by KaiserKatze** [comment]
那还不如抓包做登陆接口呢 _(:зゝ∠)_

**Comment by cnbeining** [comment]
有点小RSA加密 无伤大雅。

**Comment by KaiserKatze** [comment]
@cnbeining 酱,
话说我不是很懂POST到dologin后返回的三段数据是干嘛的_(:зゝ∠)_

**Comment by fython** [comment]
感觉 Bilibili 现在已经在收紧开放 API ，感觉我的一个坑也不得不弃了233
